apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-ts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-ts
  template:
    metadata:
      labels:
        app: express-ts
    spec:
      containers:
      - name: express-ts
        image: siddharth013/express-ts:1ac5f1f
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
