name: Build and Deploy to AWS EKS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: siddharth013/express-ts

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Image Tag from Commit SHA
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region ap-south-1 --name devops-cluster

      - name: Update K8s Deployment with New Image
        run: |
          kubectl set image deployment/express-ts express-ts=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          kubectl rollout restart deployment/express-ts

          kubectl rollout status deployment/express-ts
